version: "3.9"

services:
  tomcat-server:
    container_name: tomcat-server
    build: .
    ports:
      - "8383:8080"
    volumes:
      - ./m2_data:/root/.m2/
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    volumes:
      # - ./postgres_data:/var/lib/postgresql/data/
      - ./migrations/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8087:80
      - 4443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: dmenezes.gabriel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    depends_on:
      - postgres

  postgres-test:
    container_name: postgres-test
    image: postgres:14.0-alpine
    volumes:
      - ./migrations/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: postgres
