version: "3.9"

services:
  # ---------------------------------------------------------------------------
  # Database
  # ---------------------------------------------------------------------------
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    volumes:
      # - ./postgres_data:/var/lib/postgresql/data/
      - ./migrations/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - prod

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8087:80
      - 4443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: dmenezes.gabriel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    depends_on:
      - postgres
    networks:
      - prod

  # ---------------------------------------------------------------------------
  # Maven
  # ---------------------------------------------------------------------------
  maven:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-maven
    volumes:
      - ./.m2:/root/.m2
      - $PWD:/usr/src/mymaven
    volumes_from:
      - tomcat
    networks:
      - prod
  # ---------------------------------------------------------------------------
  # Tomcat
  # ---------------------------------------------------------------------------
  tomcat:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-tomcat
    ports:
      - "8383:8080"
    depends_on:
      - postgres
    networks:
      - prod
    env_file:
      - ./.env

  # ---------------------------------------------------------------------------
  # Tests
  # ---------------------------------------------------------------------------
  maven-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-maven-test
    command: /bin/bash -c 'mvn clean test'
    volumes:
      - ./.m2:/root/.m2
      - $PWD/src:/app/src
    depends_on:
      - postgres-test
    networks:
      - test

  postgres-test:
    container_name: postgres-test
    image: postgres:14.0-alpine
    volumes:
      - ./migrations/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - test

networks:
  prod:
  test:
