INSERT INTO T_HT_USUARIO (
  cd_usuario,
  nm_usuario,
  dt_nascimento,
  ds_genero,
  ds_email,
  ds_senha
)
SELECT SQ_USUARIO.NEXTVAL, nm_usuario, dt_nascimento, ds_genero, ds_email, ds_senha
FROM (
	SELECT
	  'Gabriel' AS NM_USUARIO ,
	  TO_DATE('12/01/1987', 'DD/MM/YYYY') DT_NASCIMENTO ,
	  'M' AS DS_GENERO ,
	  'gabriel@example.com' AS DS_EMAIL ,
	  '1234567' AS DS_SENHA
	FROM DUAL
	UNION ALL
	SELECT
	  'Joao' AS NM_USUARIO ,
	  TO_DATE('11/02/1988', 'DD/MM/YYYY') DT_NASCIMENTO ,
	  'M' AS DS_GENERO ,
	  'joao@example.com' AS DS_EMAIL ,
	  '1234567' AS DS_SENHA
	FROM DUAL
	UNION ALL
	SELECT
	  'Pedro' AS NM_USUARIO ,
	  TO_DATE('01/01/1986', 'DD/MM/YYYY') DT_NASCIMENTO ,
	  'M' AS DS_GENERO ,
	  'joao@example.com' AS DS_EMAIL ,
	  '1234567' AS DS_SENHA
	FROM DUAL
  );
-- Check
-- DELETE FROM T_HT_USUARIO;
SELECT * FROM T_HT_USUARIO;
SELECT * FROM T_HT_USUARIO WHERE cd_usuario IS NOT NULL;
SELECT * FROM T_HT_USUARIO WHERE DT_NASCIMENTO >= TO_DATE('01/02/1987', 'DD/MM/YYYY');
SELECT * FROM T_HT_USUARIO WHERE DT_NASCIMENTO BETWEEN TO_DATE('01/02/1986', 'DD/MM/YYYY') AND TO_DATE('01/02/1988', 'DD/MM/YYYY');
SELECT * FROM T_HT_USUARIO WHERE NM_USUARIO BETWEEN 'A' AND 'L';
SELECT * FROM T_HT_USUARIO thu WHERE NM_USUARIO NOT IN ('Gabriel', 'Joao');
SELECT * FROM T_HT_USUARIO WHERE TO_CHAR(DT_NASCIMENTO, 'YYYY') IN ('1986', '1988');
SELECT DISTINCT NM_USUARIO FROM T_HT_USUARIO;
